version: '3'
services:
  serviceregistry:
    image: 'danil2110/serviceregistry:0.0.1'
    container_name: serviceregistry
    ports:
      - '8761:8761'
  configserver:
    image: 'danil2110/configserver:0.0.1'
    container_name: configserver
    ports:
      - '9262:9262'
    environment:
      - EUREKA_SERVER_ADDRESS=http://host.docker.internal:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://configserver:9262/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - serviceregistry
  cloudgateway:
    image: 'danil2110/cloudgateway:0.0.1'
    container_name: cloudgateway
    ports:
      - '9090:9090'
    environment:
      - EUREKA_SERVER_ADDRESS=http://host.docker.internal:8761/eureka
      - CONFIG_SERVER_URL=host.docker.internal
    depends_on:
      configserver:
          condition: service_healthy
  orderservice:
    image: 'danil2110/orderservice:0.0.1'
    container_name: orderservice
    ports:
      - '8082:8082'
    environment:
      - EUREKA_SERVER_ADDRESS=http://host.docker.internal:8761/eureka
      - CONFIG_SERVER_URL=host.docker.internal
      - DB_HOST=host.docker.internal
    depends_on:
      configserver:
        condition: service_healthy
  productservice:
    image: 'danil2110/productservice:0.0.1'
    container_name: productservice
    ports:
      - '8080:8080'
    environment:
      - EUREKA_SERVER_ADDRESS=http://host.docker.internal:8761/eureka
      - CONFIG_SERVER_URL=host.docker.internal
      - DB_HOST=host.docker.internal
    depends_on:
      configserver:
        condition: service_healthy
  paymentservice:
    image: 'danil2110/paymentservice:0.0.1'
    container_name: paymentservice
    ports:
      - '8081:8081'
    environment:
      - EUREKA_SERVER_ADDRESS=http://host.docker.internal:8761/eureka
      - CONFIG_SERVER_URL=host.docker.internal
      - DB_HOST=host.docker.internal
    depends_on:
      configserver:
        condition: service_healthy